<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Depenk.Query\Depenk.Query.csproj" />
    <ProjectReference Include="..\Depenk.Analysis\Depenk.Analysis.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" Version="2.2.0" />
  </ItemGroup>

</Project>
