<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Depenk.Core\Depenk.Core.csproj" />
    <ProjectReference Include="..\Depenk.Scanning\Depenk.Scanning.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Depenk.Tests" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
